package:
  name: 'krater'
  version: "2.7.12"
about:
  summary: "Kmer Analysis Tool Easy to run"
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - numpy
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - matplotlib
    - jellyfish>=2
    - meryl==1.3
    - genomescope2
build:
  script: python setup.py install