package:
  name: 'krater'
  version: "2.7.9"
about:
  summary: "Kmer Analysis Tool Easy to run"
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - numpy
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - scipy
    - statsmodels
    - pandas
    - matplotlib
    - genomescope2
build:
  script: python setup.py install